SELECT * FROM TAB;

DROP TABLE MEMBER PURGE;
CREATE TABLE MEMBER(
  ID    VARCHAR2(10) PRIMARY KEY,
  PW    VARCHAR2(10) NOT NULL,
  NAME  VARCHAR2(30) NOT NULL,
  REGIDATE  DATE NOT NULL  
);

SELECT * FROM MEMBER;

-- REGIDATE 컬럼에 DEFAULT 값 설정하기
ALTER TABLE MEMBER MODIFY REGIDATE DEFAULT SYSDATE;

DESC MEMBER;

CREATE TABLE BOARD(
  NUM       NUMBER PRIMARY KEY,
  TITLE     VARCHAR2(200)  NOT NULL,
  CONTENT   VARCHAR2(2000) NOT NULL,
  ID        VARCHAR2(10) NOT NULL,
  POSTDATE  DATE DEFAULT SYSDATE NOT NULL,
  VISITCOUNT NUMBER(6),
  CONSTRAINT FK_ID FOREIGN KEY(ID) REFERENCES MEMBER(ID)
);

SELECT * FROM BOARD;

DESC BOARD;

ALTER TABLE BOARD ADD CONSTRAINT FK_ID FOREIGN KEY(ID) REFERENCES MEMBER(ID);


-- 182 PAGE
CREATE SEQUENCE SEQ_BOARD_NUM
  INCREMENT BY 1
  START WITH 1
  MINVALUE 1
  NOMAXVALUE 
  NOCYCLE
  NOCACHE;
  
  
DESC BOARD;

-- 186 PAGE
-- INSERT INTO BOARD  
-- ORA-02291: integrity constraint (TJOEUN.FK_ID) violated - parent key not found  
INSERT INTO BOARD 
       VALUES (SEQ_BOARD_NUM.NEXTVAL, '제목1입니다', '내용1입니다', 'tjoeun', SYSDATE, 0);   

DESC MEMBER;  
INSERT INTO MEMBER (ID, PW, NAME)
       VALUES ('tjoeun', '1234', '더조은');
INSERT INTO BOARD 
       VALUES (SEQ_BOARD_NUM.NEXTVAL, '제목1입니다', '내용1입니다', 'tjoeun', SYSDATE, 0);   
       
COMMIT;



SELECT id, pw, name, regidate FROM MEMBER;

SELECT * FROM MEMBER
 WHERE id = 'tjoeun'
   AND pw = '1234';
       
SELECT * FROM MEMBER;

SELECT * FROM MEMBER WHERE id = 'tjoeun' AND pw = '1234';



